config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "places#index"
  resources :places do 
    post "place_users", to: 'place_users#create'
    #post "booking", to: 'booking#create'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :places

end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :type
    belongs_to :location
    has_many :place_users
    has_many :users, :through => :place_users
    belongs_to :host, class_name: 'User', foreign_key: :host_id


    def available?(date = Date.today)
        PlaceUser.where(place_id: id)
        .where("? BETWEEN date_start AND date_end", date).none?
    end
end

app/models/place_user.rb
class PlaceUser < ApplicationRecord
    belongs_to :place
    belongs_to :user
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :places
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :place_users
  has_many :places, :through => :place_users


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/place_users_controller.rb
class PlaceUsersController < ApplicationController

    def create
       
       place_user = PlaceUser.new(place_user_params)
       #booking = Booking.new(booking_params)
       place_user.place_id = params[:place_id]
       #booking.place_id = params[:place_id]
       if current_user.nil?
         redirect_to "/users/sign_in"
       else 
         place_user.user_id = current_user.id
         if available?
            #booking.user_id = current_user.id       
            place_user.save!
            #booking.save
          end
          redirect_to "/places"
        end
       
 
    end

    def available?
         PlaceUser.where(place_id: params[:place_id]).where("? BETWEEN 
          date_start AND date_end OR 
          ? BETWEEN date_start AND date_end", place_user_params[:date_start], 
          place_user_params[:date_end]).none?

    end

    private


    def place_user_params
        params.require(:place_user).permit(:date_start, :date_end)
    end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
    def index
        @places = Place.all
    end

    def new
        @place = Place.new

    end

    def edit
        @place = Place.find(params[:id])
    end

    def update
        @place = Place.find(params[:id])
        @place.update(place_params)
        redirect_to "/places"
    end

    def create

        @place = Place.new(place_params)
        @place.host_id = current_user.id
        @place.save!
        redirect_to "/places"
    end

    def show
        @place = Place.find(params[:id])
        @place_user = PlaceUser.new
        #@booking = Booking.new
    end

    def destroy
        @place = Place.find(params[:id])
        @place.destroy
        redirect_to "/places"
    end

    private

    def place_params
        params.require(:place).permit(:available, :size, :price, :photo, :description, :location_id, :type_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar_header.html.erb
<style type="text/css">
  .navbar {
    padding-left: 25px;
    margin: 10px;
    margin-bottom: 20px;
    border-bottom: 1px solid gray;
  }
  li {
    list-style: none;
  }

</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed">
  <a class="navbar-brand" href="#">Lilibnb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled"<%= link_to "My profile", current_user %></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lilibnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= render "layouts/navbar_header" %>
    <%= yield %>
  </body>
</html>

app/views/places/_new_listing_form.html.erb
<%= form_for @place, :html => {:class => "form-horizontal center"} do |f| %>
      <div class="form-group">
        <%= f.label :photo, "Photo_URL:", class: "col-md-4 control-label"  %>
        <div class="col-md-4">
          <%= f.text_field  :photo, class: "form-control",  placeholder: "Photo_URL" %>
        </div>
        <div class="form-group">
        <%= f.label :size, "Size:", class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= f.text_field :size, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :price, "Price per night:", class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= f.text_field :price, class: "form-control", placeholder: "Price per night" %>
        </div>
        <div class="form-group">
        <%= f.label :description, "Description:", class: "col-md-4 control-label" %>
        <div class="col-md-4">
          <%= f.text_area :description, class: "form-control", placeholder: "Give a short description" %>
        </div>
        <div class="form-group">
        <%= f.label :type, "Type of bnb:", class: "col-md-4 control-label" %>
        <div class="col-md-4">
        <%= f.select :type_id, options_for_select(Type.all.map{|t| [t.name, t.id]}), { :include_blank => "Please select category"}, {:class => "form-control"} %>
        </div>
        <div class="form-group">
        <%= f.label :location, "Location:", class: "col-md-4 control-label" %>
        <div class="col-md-4">
        <%= f.select :location_id, options_for_select(Location.all.map{|t| [t.country, t.id]}), { :include_blank => "Please select your country"}, {:class => "form-control"} %>
        </div>




      

      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
 <% end %>

app/views/places/_reservations_form.html.erb
<div class="container">

<%= form_for @place_user, url: place_place_users_path(@place,@place_user ) ,method: :post, :html => {:class => "form-horizontal center"} do |f| %>
      
        <div class="form-group">
        <%= f.label :date_start, "Date-start:", class: "col-md-4 control-label" %>
       
        <div class="col-md-4">
          <%= select_date Date.today, :prefix => :place_user  %>
        </div>
        
    </div>
    <div class="form-group">
    <%= f.label :date_end, "Date-end:", class: "col-md-4 control-label" %>
    
    
    <%= select_date Date.today, :prefix => :place_user %>
        
             

      <%= f.submit "Book the place", class: "btn btn-default btn-primary" %>  
 <% end %>

</div>

app/views/places/edit.html.erb
<%= render "new_listing_form" %>

app/views/places/index.html.erb
<div class="container no-gutter">

  <% @places.each do |place| %>
  
    <li>
      <a href="/places/<%= place.id%>">
      <div class="col-sm-3">
        <div class="row">
          <div><img src="<%= place.photo %>"></div>
          <div><h5><%= place.description %></h5></div>
          <div><h6>$<%= place.price %> per night</h6></div>
          <br>
          <div class="type"><%= place.type.name %></div>
        </a>
    
           <% end %>
        </div>
     </div>
    </li>
</div>
<div><%= link_to 'New',  "/places/new", method: :get, class: 'btn btn-primary' %><div>

  <%= link_to "My profile", current_user %>

app/views/places/new.html.erb
<%= render "new_listing_form" %>

app/views/places/show.html.erb
<h1>AirBnB</h1>

<div>


<div class="container col-4">
<img src="<%=@place.photo%>">
<div><%= link_to 'Edit',  "/places/#{@place.id}/edit", method: :get, class: 'btn btn-primary' %><div>
</div>
<div><%= link_to 'Back',  "/places/", method: :get, class: 'btn btn-primary' %><div>
</div>
</div>
<div><%= link_to 'Delete',  "/places/#{@place.id}", method: :delete, class: 'btn btn-primary' %><div>

<%= render "reservations_form" %>

app/views/users/show.html.erb
<div class="container">
    <h1>  Email: <%= @user.email %> </h1>
</div>